config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :users, only: [:show, :edit, :update, :destroy] 

  #Clearance
  get "/sign_in" => "session_clearances#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  post "sign_in" => "session_clearances#create"

  #home
  get "/about" => "homes#about", as: "about"
  get "/contact_us" => "homes#contact", as: "contact"
 
  resources :homes
  root 'homes#cover'

  # OmniAuth Facebook
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  # Redirect to root if page not FOUND
  get ':not_found', to: redirect('/') 
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
   belongs_to :user

    def self.create_with_omniauth(auth_hash)
      create! do |auth|
        auth.provider = auth_hash["provider"]
        auth.uid = auth_hash["uid"]
        auth.token = auth_hash["credentials"]["token"]
      end
    end

    def update_token(auth_hash)
      self.token = auth_hash["credentials"]["token"]
      self.save
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  # Associations
  has_many :authentications, :dependent => :destroy
  #Validations
  validates_presence_of :email, :message => 'must be included'
  validates_presence_of :encrypted_password, :message => '%{value} must be included'
  
 
   def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
      u.name = auth_hash["info"]["name"]
      u.email = auth_hash["extra"]["raw_info"]["email"]
      byebug
      u.authentications<<(authentication)
      u.password = "123456"
      u.save
    end
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < ApplicationController
  if respond_to?(:before_action)
    before_action :redirect_signed_in_users, only: [:create, :new]
    skip_before_action :require_login, only: [:create, :new], raise: false
    skip_before_action :authorize, only: [:create, :new], raise: false
  else
    before_filter :redirect_signed_in_users, only: [:create, :new]
    skip_before_filter :require_login, only: [:create, :new], raise: false
    skip_before_filter :authorize, only: [:create, :new], raise: false
  end

  def new
    @user = user_from_params
    render template: "users/new"
  end

  def create
    @user = user_from_params
     if @user.save
      sign_in @user
      flash[:info] = "You are sucessfully Log In!"
      redirect_back_or url_after_create
    else 
      flash.now[:danger] = @user.errors.full_messages
      render template: "users/new"
    end
  end

  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
    email = user_params.delete(:email)
    password = user_params.delete(:password)
    name = user_params.delete(:name)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
      user.name = name
    end
  end

  def user_params
    params[:user] || Hash.new
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :require_login, only: :show

  def index
  end

  def show
  end

  def cover
  	render "homes/cover"
  end

  def about 
  	render "homes/about"
  end

  def contact 
  	render "homes/contact_us"
  end
end

app/controllers/session_clearances_controller.rb
class SessionClearancesController < Clearance::SessionsController
  layout "sign_in"

  def new
    @user = User.new 
  end

	def create
    @user = authenticate(params)

    sign_in(@user) do |status|
      if status.success?
      	flash[:success] = "You are successfully Log In"
        redirect_back_or url_after_create

      else
      	#flash.now[:error] = status.failure_message

        if User.find_by_email(params[:session][:email]).nil?
          flash.now[:danger] = "#{params[:session][:email]} is not valid."
        else
          flash.now[:danger] = "Invalid password."
        end

        render "new", status: :unauthorized
      end
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
  def create_from_omniauth
    auth_hash = request.env["omniauth.auth"]

    authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) || Authentication.create_with_omniauth(auth_hash)
  
    if authentication.user
      user = authentication.user 
      authentication.update_token(auth_hash)
      @next = root_url
      flash[:success] = "Signed in!"
    else
      user = User.create_with_auth_and_hash(authentication,auth_hash)
      @next = edit_user_path(user)   
      flash[:success] = "User created - confirm or edit details..."
    end
    sign_in(user)
    redirect_to @next
  end

  private 
    def message(type) 
      type
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  	@user = current_user
    render :layout => false
  end

  def edit
  	@user = current_user
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update_attributes(user_params)
  	  redirect_to user_path(:id => current_user.id), :notice => "Your account have been updated!"
  	else
      flash.now[:error] = "Invalid input, Please Try again"
  	  render "edit"
  	end
  end

  private 
  def user_params 
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def custom_title(title)
	  @custom_title = "QuoraCloneClearance| #{title}"
	end

	def title
	 @title = "QuoraCloneClearance"
	end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/session_clearances_helper.rb
module SessionClearancesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_clearances_helper.rb
module UserClearancesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<div id = "card_cover" class="inner cover">
<h1 class="cover-heading">About</h1>
<p id = "about_text" class="lead">Founded in August of 2008 and based in San Francisco, California, Airbnb is a trusted community marketplace for people to list, discover, and book unique accommodations around the world — online or from a mobile phone or tablet.

Whether an apartment for a night, a castle for a week, or a villa for a month, Airbnb connects people to unique travel experiences, at any price point, in more than 34,000 cities and 190 countries. And with world-class customer service and a growing community of users, Airbnb is the easiest way for people to monetize their extra space and showcase it to an audience of millions.</p>

</div>

app/views/homes/contact_us.html.erb
      <br>
      <br>
      <div id="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3983.9015133212056!2d101.60995831447383!3d3.120746254197571!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31cc4eadb189222d%3A0x9cdd7bfc6db179d8!2s23%2C+Lorong+SS+23%2F6e%2C+Taman+Sea%2C+47400+Petaling+Jaya%2C+Selangor!5e0!3m2!1sen!2smy!4v1457027517094" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
      </div>

      <p>For more enquiries,You can drop us an <a id="email" href="mailto:airbnbtest3@gmail.com" data-toggle="tooltip" title="airbnbtest3@gmail.com">email </a></p>

      <script>
      var map, infoBubble, infoBubble2;
      function init() {
        var mapCenter = new google.maps.LatLng({lat: 3.1207329, lng: 101.61212999999998});
        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 8,
          center: mapCenter,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        });
        var marker = new google.maps.Marker({
          map: map,
          position: new google.maps.LatLng(3.1207329  , 101.61212999999998),
          draggable: true
        });

        var contentString = '<div id="content">'+
        '<h1>Venue</h1>'+
        '<p>No 23, Lorong SS23/6E</p>'+
        '<p>Taman SEA</p>'+
        '<p>47400 Petaling Jaya</p>'+
        '<p>Selangor Dahrul Ehsan</p>'+
        '<p>Malaysia</p>'+
        '</div>';

        infoBubble = new InfoBubble({
          maxWidth: 300,
        });

        infoBubble2 = new InfoBubble({
          map: map,
          content: '<div class="phoneytext">Some label</div>',
          position: new google.maps.LatLng(-35, 151),
          shadowStyle: 1,
          padding: 0,
          backgroundColor: 'rgb(57,57,57)',
          borderRadius: 4,
          arrowSize: 10,
          borderWidth: 1,
          borderColor: '#2c2c2c',
          disableAutoPan: true,
          hideCloseButton: true,
          arrowPosition: 30,
          backgroundClassName: 'phoney',
          arrowStyle: 2
        });

        infoBubble.open(map, marker);
        infoBubble2.open();

        var div = document.createElement('DIV');
        div.innerHTML = 'Hello';

       // infoBubble.addTab('A Tab', div);
        infoBubble.addTab('We are At Here', contentString);

        google.maps.event.addListener(marker, 'click', function() {
          if (!infoBubble.isOpen()) {
            infoBubble.open(map, marker);
          }
        });

     

      }

      google.maps.event.addDomListener(window, 'load', init);

      function updateStyles() {
        var shadowStyle = document.getElementById('shadowstyle').value;
        infoBubble.setShadowStyle(shadowStyle);

        var padding = document.getElementById('padding').value;
        infoBubble.setPadding(padding);

        var borderRadius = document.getElementById('borderRadius').value;
        infoBubble.setBorderRadius(borderRadius);

        var borderWidth = document.getElementById('borderWidth').value;
        infoBubble.setBorderWidth(borderWidth);

        var borderColor = document.getElementById('borderColor').value;
        infoBubble.setBorderColor(borderColor);

        var backgroundColor = document.getElementById('backgroundColor').value;
        infoBubble.setBackgroundColor(backgroundColor);

        var maxWidth = document.getElementById('maxWidth').value;
        infoBubble.setMaxWidth(maxWidth);

        var maxHeight = document.getElementById('maxHeight').value;
        infoBubble.setMaxHeight(maxHeight);

        var minWidth = document.getElementById('minWidth').value;
        infoBubble.setMinWidth(minWidth);

        var minHeight = document.getElementById('minHeight').value;
        infoBubble.setMinHeight(minHeight);

        var arrowSize = document.getElementById('arrowSize').value;
        infoBubble.setArrowSize(arrowSize);

        var arrowPosition = document.getElementById('arrowPosition').value;
        infoBubble.setArrowPosition(arrowPosition);

        var arrowStyle = document.getElementById('arrowStyle').value;
        infoBubble.setArrowStyle(arrowStyle);

        var closeSrc = document.getElementById('closeSrc').value;
        infoBubble.setCloseSrc(closeSrc);
      }

      function addTab() {
        var title = document.getElementById('tab-title').value;
        var content = document.getElementById('tab-content').value;

        if (title !== '' && content !== '') {
          infoBubble.addTab(title, content);
        }
      }

      function updateTab() {
        var index = document.getElementById('tab-index-update').value;
        var title = document.getElementById('tab-title-update').value;
        var content = document.getElementById('tab-content-update').value;

        if (index) {
          infoBubble.updateTab(index, title, content);
        }
      }

      function removeTab() {
        var index = document.getElementById('tab-index').value;
        infoBubble.removeTab(index);
      }
    </script>
    

app/views/homes/cover.html.erb
<div class="inner cover">
<h1 class="cover-heading">MYB2B Reservation</h1>
<p class="lead">Start your Hotel Reservation by Joining US today!</p>
<p class="lead">
  <a href="#" class="btn btn-lg btn-default">Log In/Sign Up</a>
</p>
</div>

app/views/homes/index.html.erb
<% if signed_in? %>
  <p><%= link_to "Profile", user_path(:id => current_user.id) %></p>
  <%= current_user.email %>
<% else %>
<div class="other-links">
    <% if Clearance.configuration.allow_sign_up? %>
      <%= link_to t(".sign_up"), sign_up_path %>
      <%= link_to "Facebook Login", "/auth/facebook" %>
    <% end %>
    <%= link_to t(".forgot_password"), new_password_path %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuoraCloneClearance</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maps.googleapis.com/maps/api/js"></script>

  <%= csrf_meta_tags %>
</head>
<body>
  <div class="site-wrapper">
    <div class="site-wrapper-inner">
      <div class="cover-container">
        <%= render "partials/home/header" %>
        <%= yield %>
        <%= render "partials/home/footer" %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/layouts/sign_in.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= custom_title("sign_in") %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1 class="title"><%= title %> </h1> 

  <br>
  <div class="container">
    <% flash.each do |key, value|%>
      <div class="alert alert-<%= key %>"><%=value %></div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>

app/views/partials/home/_footer.html.erb
<div class="mastfoot">
	<div class="inner">
	  <p>&copy MyBnb Updated 2016, by <a href="https://github.com/yclim95">YC Lim</a>.</p>
	</div>
</div>

app/views/partials/home/_header.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand"><%= title %></h3>
    <nav>
      <ul class="nav masthead-nav">
        <li class="active"><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact Us", contact_path %></li>
      </ul>
    </nav>
  </div>
</div>

app/views/session_clearances/new.html.erb
   <div id="header">
    <% if signed_in? -%>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
      <%= current_user.name %>
    <% else %>
       <%= form_for :session, url: sign_in_path do |form| %>
      <div class="text-field">
        <%= form.label :email %>
        <%= form.text_field :email, type: 'email' %>
      </div>

      <div class="password-field">
        <%= form.label :password %>
        <%= form.password_field :password %>
      </div>

      <div class="submit-field">
        <%= form.submit %>
      </div>

      <div class="other-links">
        <% if Clearance.configuration.allow_sign_up? %>
          <%= link_to t(".sign_up"), sign_up_path %>
        <% end %>
        <%= link_to t(".forgot_password"), new_password_path %>
      </div>

    <% end %>
    <% end %>
  </div>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/edit.html.erb
<p>Edit Profile</p>

 <%= form_for @user do |form| %>
    <div class="name-field">
    <%= form.label :name %>
    <%= form.text_field :name %>
    </div>

    <div class="text-field">
    <%= form.label :email %>
    <%= form.text_field :email, type: 'email' %>
    </div>

    <div class="password-field">
    <%= form.label :password %>
    <%= form.password_field :password %>
    </div>

    <div class="submit-field">
      <%= form.submit "Update Post" %>
    </div>

  <% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <div class="name-field">
    <%= form.label :name %>
    <%= form.text_field :name %>
    </div>

    <div class="text-field">
    <%= form.label :email %>
    <%= form.text_field :email, type: 'email' %>
    </div>

    <div class="password-field">
    <%= form.label :password %>
    <%= form.password_field :password %>
    </div>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuoraCloneClearance</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<h1 class="title"><%= title %> </h1> 
	<h2>Dear <%= current_user.name %></h2>
	<p><%= current_user.email %></p>

	<%= button_to "Edit Profile", edit_user_path, form: {target: '_blank'},:method => :get, :class => "btn" %>
	<br>
	<%= link_to "Back to Home", root_path %>

</body>
</html>